version: '3.8'

services:
  sup-api:
    build:
      context: ./sup-api
    image: sup/sup-api:1.0.0
    container_name: sup-api
    ports:
      - '8085:8085'

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sup_db_container:5432/sup_db
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    depends_on:
      - postgres_db

  sup-website:
    build:
      context: ./sup-website
    image: sup/sup-website:1.0.0
    container_name: sup-website
    ports:
      - '4000:80'
    depends_on:
      - sup-api

  postgres_db:
    container_name: sup_db_container
    image: postgres:latest
    restart: always # when you turn off the computer and then turn on, it will run it.
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgresvolume:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.dl/schema.sql

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_DEFAULT_ADDRESS: 6000
      PGADMIN_LISTEN_PORT: 6000
    expose:
      - 6000
    ports:
      - "7000:6000"
    volumes:
      - pgadminvolume:/var/lib/pgadmin

volumes:
  postgresvolume:
  pgadminvolume:
